#ifndef SEAFILE_CLIENT_UTILS_GEN_RANDOM_PASSWD_H
#define SEAFILE_CLIENT_UTILS_GEN_RANDOM_PASSWD_H

int generateRandomPasswd(char* &s, const int len);

#endif // SEAFILE_CLIENT_UTILS_GEN_RANDOM_PASSWD_H
